---
title: "Simulations"
author: "Allen Bush"
date: "2023-02-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls()) # clear workspace

library(tidyverse)
library(brms)
library(cmdstanr)
library(tidybayes)
library(ggridges)

```

#adapted from: https://bookdown.org/content/4857/monsters-and-mixtures.html#zero-inflated-outcomes
```{r}
# define parameters
prob_drink <- 0.2  # 20% of days
rate_work  <- 6    # average 6 manuscript per day

# sample size
n <- 1200

# simulate days monks drink
set.seed(365)
drink <- rbinom(n, size = 1, prob = prob_drink)
hist(drink)

# simulate manuscripts completed
y <- (1 - drink) * rpois(n, lambda = rate_work)

hist(y)
```
#adapted from: https://bookdown.org/content/3686/tools-in-the-trunk.html#censored-data-in-jags-brms
```{r}
d <- tibble(y = y)


# values below 2 are censored
t1 <- 2


d <-
  d %>% 
  mutate(y1   = if_else(y < t1, t1, y),
         cen1 = if_else(y < t1, "left", "none")) %>%
   mutate(y_na = ifelse(cen1 == "none", y, NA))

d
```

Histograms
```{r}
d %>% 
  pivot_longer(-cen1) %>% 
  mutate(name = factor(name, levels = c("y", "y1", "y_na"))) %>% 
  
  ggplot(aes(x = value)) +
  geom_histogram(linewidth = 0.25, binwidth = 1, 
                 fill = "skyblue4", color = "white") +
  xlab(NULL) +
  scale_y_continuous(NULL, breaks = NULL) +
  facet_wrap(~ name, ncol = 3)
```

Interval censoring from 2 to 4
```{r}
t2 <-2

t3 <- 4


d <-
  d %>% 
  mutate(y2   = if_else(y >= t2 & y < t3, t2, y),
         y3   = if_else(y >= t2 & y < t3, t3, y),
         cen2 = if_else(y >= t2 & y < t3, "interval", "none")) %>% 
  mutate(y_na = ifelse(cen2 == "none", y, NA))%>% 
  mutate(y4   = if_else(y >= t2 & y < t3, t2, 
                        if_else(y < t1, t1, y)),
         y5   = if_else(y >= t2 & y < t3, t3, y),
         cen3 = if_else(y >= t2 & y < t3, "interval",
                       if_else(y < t1, "left", "none"))) %>% 
  mutate(y_na = ifelse(cen3 == "none", y, NA))

d
```

Histograms
```{r}
d %>% 
  pivot_longer(cols = c(y, y4, y5, y_na)) %>% 
  mutate(name = factor(name, levels = c("y", "y4", "y5", "y_na"))) %>% 
  
  ggplot(aes(x = value)) +
  geom_histogram(linewidth = 0.25, binwidth = 1, 
                 fill = "skyblue4", color = "white") +
  labs(subtitle = "Our data have been updated, again",
       x = NULL) +
  scale_y_continuous(NULL, breaks = NULL) +
  facet_wrap(~ name, ncol = 2)
```

Model adapted from both previous links
```{r}
censored.ZIP.1 <-
  brm(data = d,
      family = zero_inflated_poisson,
      y4 | cens(cen3, y5) ~ 1,
      prior = c(prior(normal(1, 0.5), class = Intercept),
                prior(beta(2, 6), class = zi)),  # the brms default is beta(1, 1)
      iter = 2000, warmup = 1000, chains = 4, cores = 4,
      seed = 12,
      backend = "cmdstanr",
      file = "censored.ZIP.1")

print(censored.ZIP.1)
```

function for geom_hist
```{r}
geom_hist <- function(xintercept = xintercept, binwidth = binwidth, ...) {
  
  list(
    geom_histogram(fill = "skyblue", color = "white", linewidth = 0.2, binwidth = binwidth, boundary = 106),
    geom_vline(xintercept = xintercept, color = "skyblue3", linewidth = 1/2, linetype = 3),
    stat_pointinterval(aes(y = 0), point_interval = mode_hdi, .width = .95),
    scale_y_continuous(NULL, breaks = NULL)
  )
  
}
```

Draws
```{r}
draws<- d %>%
  add_predicted_draws(censored.ZIP.1, ndraws = 50)


ZIP.actualdata <- ggplot(data = draws) +
  geom_histogram(aes(x = y, y = ..density..),  
                 fill = "skyblue4", color = "white", binwidth = 1) +
  geom_density(aes( x = .prediction,  group = .draw),
            size  = 1/4, alpha = 1/3, color = "lightblue") +
  labs(title = "Actual Data") +
  theme_classic()


ZIP.censoreddata <- ggplot(data = draws) +
  geom_histogram(aes(x = y4, y = ..density..),  
                 fill = "skyblue4", color = "white", binwidth = 1) +
  geom_density(aes( x = .prediction,  group = .draw),
            size  = 1/4, alpha = 1/3, color = "lightblue") +
  labs(title = "Censored Data") +
  theme_classic()
```

naive model
```{r}
naive.ZIP.1 <-
  brm(data = d,
      family = poisson,
      y_na| trunc(lb = 4) ~ 1,
      prior = prior(normal(1, 0.5), class = Intercept),
      iter = 2000, warmup = 1000, chains = 4, cores = 4,
      seed = 12,
      backend = "cmdstanr",
      file = "naive.ZIP.1")

print(naive.ZIP.1)
```
Draws
```{r}
draws2<- d %>%
  add_predicted_draws(naive.ZIP.1, ndraws = 50)


naive.actualdata <- ggplot(data = draws2) +
  geom_histogram(aes(x = y, y = ..density..),  
                 fill = "skyblue4", color = "white", binwidth = 1) +
  geom_density(aes( x = .prediction,  group = .draw),
            size  = 1/4, alpha = 1/3, color = "lightblue") +
  labs(title = "Actual Data") +
  theme_classic()


naive.censoreddata <- ggplot(data = draws2) +
  geom_histogram(aes(x = y_na, y = ..density..),  
                 fill = "skyblue4", color = "white", binwidth = 1) +
  geom_density(aes( x = .prediction,  group = .draw),
            size  = 1/4, alpha = 1/3, color = "lightblue") +
  labs(title = "Censored Data") +
  theme_classic()
```
