---
title: "unclean_data_viz"
author: "Allen Bush"
date: "2023-02-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges)
library(readxl)

pest_conc <- read_excel("master_pesticides.xlsx")
pest_detect <- read_excel("pesticide_detection.xlsx")

```


#Data manipulation
```{r}
pest_conc_long <- pest_conc %>% pivot_longer(cols = one.naphthol:fludioxonil, names_to = "pesticide", values_to = "recorded_concentration")

pest_master_long <- right_join(pest_conc_long, pest_detect, by = "pesticide")

pest_master_long <- pest_master_long %>%
  mutate(concentration = as.numeric(ifelse(recorded_concentration == "nd", 0, 
                                            ifelse(recorded_concentration == "<LOQ", LOD, recorded_concentration))), # NAs introduced by coercion -> from samples in 2013 where recorded_concentration == NA just remove for now
         status = ifelse(recorded_concentration == "nd", "nd", 
                                            ifelse(recorded_concentration == "<LOQ", "<LOQ", "quantified"))) %>%
  drop_na(concentration)

```
#data summary
```{r}
pest_master_long %>%
  subset(status == "quantified") %>%
  group_by(pesticide, status) %>%
    summarise(n = length(concentration)) %>%
  ggplot(aes(x=pesticide, y = n)) +
  geom_bar(stat = "identity") +
  coord_cartesian(ylim = c(0,350))+
  scale_y_continuous(breaks = seq(from = 0, to = 350, by = 25))+
  geom_hline(yintercept = 50, linetype = 2)+
  geom_hline(yintercept = 25)+
  theme_classic() +
  theme(axis.text.x = element_text(angle=90, vjust = -0.1))




```


#Data viz
```{r}
pest_master_long %>%
  subset(status == "quantified") %>%
  #subset(pesticide == c("atrazine", "clothianidin", "imazethapyr", "metolachlor") ) %>%
  ggplot() +
  geom_density(aes( x = concentration)) +
  facet_wrap(~pesticide, scales = "free")
```




```{r}
pest_master_long %>%
  subset(status == "quantified") %>%
  group_by(pesticide, LOQ) %>%
  summarise(mean_conc = mean(concentration),
            n_quant = length(concentration)) %>%
  mutate(dummy = 1:length(mean_conc)) %>%
  ggplot() +
  geom_point(aes(y = mean_conc, x = as.factor(dummy)), color = "red") +
  geom_point(aes(y = LOQ, x = as.factor(dummy)), color = "green") +
  facet_wrap(~pesticide, scales = "free") +
  theme_classic()

pest_master_long %>%
  subset(status == "quantified") %>%
  group_by(pesticide, LOQ) %>%
  summarise(mean_conc = mean(concentration),
            n_quant = length(concentration)) %>%
  mutate(ratio = mean_conc/LOQ) %>%
  ggplot() +
  geom_point(aes(x = n_quant, y = ratio, color = pesticide)) +
  geom_smooth(aes(x = n_quant, y = ratio), method = "lm")


```

